language: csharp
solution: ExpediaCodingExercise.sln
 
install:
  - sudo apt-get install nunit-console
  - nuget restore ExpediaCodingExercise.sln
 
script:
  - xbuild ExpediaCodingExercise.sln
  - nunit-console ./UnitTesting/bin/Debug/UnitTesting.dll
