language: csharp
solution: ExpediaCodingExercise.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore ExpediaCodingExercise.sln
after_script:
  - nunit-console ./UnitTesting/bin/Debug/UnitTesting.dll
